packages:
  - vendor/*
  - packages/*
  - examples/foundation

linkWorkspacePackages: true

overrides:
  '@karaka/cosmokit': 'link:vendor/cosmokit'
  '@karaka/schemastery': 'link:vendor/schemastery'

peerDependencyRules:
  allowedVersions:
    typescript: '>=5 <7'

allowBuilds:
  esbuild: true
  koffi: set this to true or false
  lefthook: set this to true or false
  node-addon-require-builtin: false
  node-pty: set this to true or false
